# Generated by Django 4.0.4 on 2022-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_orders_cost_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost_rub2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
