# Generated by Django 4.0.4 on 2022-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orders_cost_rub2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost_rub2',
        ),
    ]
