# Generated by Django 4.0.4 on 2022-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
